### ISSUE TITLE
Embedded framework requires 8.3

### ISSUE THREAD

**Issue by alexcurylo** [MrAlek/Swiftalytics#3]
Moving past #1 _(thanks!)_ I get the complaint trying to link Carthage's framework `Module file's minimum deployment target is ios8.3 v8.3`. From the README seems that should be 8.0, as my application is. Is it actually 8.3?

**Comment by MrAlek** [comment]
Aah, I had never set the deployment target manually so it went for the base SDK version. Fixed now and pushed a new tag for version 0.1.1. Thanks for reporting!

**Comment by alexcurylo** [comment]
Working great now, thanks again!
