### ISSUE TITLE
update for swift 3...

### ISSUE THREAD

**Issue by sirvon** [MrAlek/Swiftalytics#8]
thanks for this incredible lib.
been getting this error lately..

``` swift
/Carthage/Build/iOS/Swiftalytics.framework/Swiftalytics compiled with 
older version of Swift language (2.0) than previous files (3.0) for architecture armv7
```

**Comment by MrAlek** [comment]
Hey! Yeah I haven't made the Swift 3 upgrade yet. Will try to fix tonight!

**Comment by MrAlek** [comment]
Release 0.4 is now written with Swift 3.0 :)
